% Aaron M. Allen, 2018.10.31
% This script uses the JAABADetect functio to apply JAABA classifiers in the JABfilelist.txt from the JABFromFlyTracker
% to videos that have been tracked with the Caltech FlyTracker. This script assume the directory structure that is
% generated by this tracker. 


addpath(genpath('/home/goodwintracking/TheCompleteFlyTrackingBundle/WholePlate'));
addpath /home/goodwintracking/TheCompleteFlyTrackingBundle/JAABA-master/perframe;
JABFiles = '/home/goodwintracking/TheCompleteFlyTrackingBundle/JABsFromFlyTracker/JABfilelist.txt';
wingJAB = '/home/goodwintracking/TheCompleteFlyTrackingBundle/JABsFromFlyTracker/WingGesture.jab';

% Apply Classifiers
% ==========================================================================
dirs = dir();
CurrDir = (pwd);
diary('JAABA_logfile.log')
for p = 1:numel(dirs)
    if ~dirs(p).isdir
      continue;
    end
    JAABAname = dirs(p).name;
    if ismember(JAABAname,{'.','..'})
      continue;
    end 
    diary on
    cd (JAABAname);
    JAABAdir =(pwd);
    
    
    % Added a bit of code to asses the number of flies per chamber, and if it varies
    % between chambers, to delete the offending rows from the trx.mat file. The Classifiers
    % have been trained assuming that there are 2 flies in each chamber, and won't work if
    % there isn't (except maybe the WingGesture).

    TrackFile = dir('*track.mat');
    load(TrackFile.name);
    cd ([JAABAname '_JAABA']);
    disp('Loading trx.mat')
    load('trx.mat');

    % Determining the average number of flies per chamber
    TotalFlies = 0;
    for F = 1:size(trk.flies_in_chamber,2)
        TotalFlies = TotalFlies + size(trk.flies_in_chamber{F},2);
    end
    FliesPerChamber = TotalFlies/size(trk.flies_in_chamber,2);

    % If the average flies per chamber is between 1 and 2 (ie was supposed to be 2, but
    % a fly died or escaped from a chamber), then the below deletes the entry in the trx.mat
    % file for the remaining fly in the offending chambers. This will allow the social
    % classifiers to be applied without issue.
    if (1 < FliesPerChamber) && (FliesPerChamber < 2)
        disp('The number of flies differs between chambers.');
        save('trxBackup.mat', 'trx', 'timestamps');
        
        % 2019.01.03 - added sections to deal with a single fly in a
        % chamber that isn't at the end of the trx and perframe data. First
        % I make a logical array for the id's that are in a 1 fly chamber,
        % then delete the rows from the trx file, then renumber the id's in
        % the trx file, then apply the logical array to delete the columns
        % in the perframe data.
        disp('Creating logical array for perframe data.');
        LM = [];
        for N = 1:size(trk.flies_in_chamber,2)
            if size(trk.flies_in_chamber{N},2) == 1
                LM = [LM, 1];
            else
                LM = [LM, 0, 0];
            end
        end
        LM = boolean(LM);
        disp(['Deleting row(s) in trx file.']);
        for N = 1:size(trk.flies_in_chamber,2)
            if size(trk.flies_in_chamber{N},2) == 1
                trx([trx.id]==trk.flies_in_chamber{N}) = [];
            end
        end
        disp('Re-numbering Ids in trx file.');
        for I = 1:length(trx)
            trx(I).id = I;
        end
        save('trx.mat', 'trx', 'timestamps')

        cd perframe
        mkdir BackupPerframe
        perframeDataFiles = dir('*.mat');
        for P = 1:length(perframeDataFiles)
            copyfile(perframeDataFiles(P).name, ['BackupPerframe/Backup_' perframeDataFiles(P).name]);
            load(perframeDataFiles(P).name);
            disp(['Deleting data from ' perframeDataFiles(P).name]);
            data(:,LM)=[];
            save(perframeDataFiles(P).name, 'data', 'units');
        end
        cd .. 
        % end of new bit ...
        
    else
        if (FliesPerChamber == 2)
            disp('There are 2 flies per chamber.')
        else
            if (FliesPerChamber == 1)
                disp('There is 1 fly per chamber.')
            end
        end
    end
    cd (JAABAdir);
    disp(['Now applying classifiers for: ' JAABAname]);
    if (round(FliesPerChamber)==2)
        error_handling_wrapper('JAABA_errors.log','JAABADetect',[JAABAname '_JAABA'],'jablistfile',JABFiles);
    else
        error_handling_wrapper('JAABA_errors.log','JAABADetect',[JAABAname '_JAABA'],'jabfiles',wingJAB);
    end
    diary off
    cd (CurrDir)
end
exit
