#!/usr/bin/env Rscript


# Author: Aaron Munro Allen
# Date: 2021-11-19

## Description:

## extract_all_data
##   Functions to extract all data generated by the Caltech FlyTracker and JAABA
##   packages written in Matlab.


## extract_track_data
##   Function to extract data from the "track.mat" file generated by the Caltech FlyTracker
##   package written in Matlab.

## extract_feat_data
##   Function to extract data from the "feat.mat" file generated by the Caltech FlyTracker
##   package written in Matlab.

## extract_jaaba_data
##   Function to extract data from the JAABA scores files generated by the JAABA package written in Matlab.
##   This function first checks for  "*_id_corrected.mat" files, generated by reassign_identities.m function.
##   If "*_id_corrected.mat" files cannot be found, then it loads the original scores files. The files are
##   of the form "scores_<behaviour>_id_corrected.mat" or "scores_<behaviour>.mat".




## Dependencies:
##     'tidyverse' package
##         install.packages("tidyverse")
##     'R.matlab' package
##         install.packages("R.matlab")
##     'data.table' package
##         install.packages("data.table")

## This function was written using R 4.x.x, tidyverse 1.x.x, and data.table 1.x.x






extract_all_data <- function(tracking_dir_path, flies_per_arena=2, save_data=FALSE) {
    suppressMessages(library("data.table"))
    suppressMessages(library("tidyverse"))
    suppressMessages(library("R.matlab"))

    if ( .Platform$OS.type == "windows" ) {
        tracking_dir_path <- tracking_dir_path %>% stringr::str_replace_all(pattern = "\\\\", "/")
    }
    if ( !stringr::str_detect(tracking_dir_path, "/$") ) {
        tracking_dir_path <- paste0(tracking_dir_path, "/")
    }

    vid_name <- tracking_dir_path %>% stringr::str_extract(pattern = "[^/]*/$") %>% stringr::str_remove(pattern = "/")
    cat(paste0("Video name is :    ", vid_name,"\n"))

    cat(paste0("    Now extracting track data\n"))
    my_track_data <- extract_track_data(paste0(tracking_dir_path, vid_name, "/", vid_name, "-track.mat"))
    cat(paste0("    Now extracting feat data\n"))
    my_feat_data <- extract_feat_data(paste0(tracking_dir_path, vid_name, "/", vid_name, "-feat.mat"))

    # test if there are any jaaba scores files to extract
    jaaba_path <- paste0(tracking_dir_path, vid_name, "/", vid_name, "_JAABA/")
    jaaba_scores_exist <- !purrr::is_empty(list.files(jaaba_path) %>% stringr::str_subset("scores_"))
    if (jaaba_scores_exist) {
        cat(paste0("    Now extracting jaaba data\n"))
        my_jaaba_data <- extract_jaaba_data(jaaba_path)
    }

    cat(paste0("    Now merging all data\n"))
    my_data <-dplyr::bind_rows(my_track_data,my_feat_data)
    if (jaaba_scores_exist) {
        my_data <- dplyr::bind_rows(my_data,my_jaaba_data)
    }
    my_data <- my_data %>%
        dplyr::mutate(Video_name = vid_name,
                      Arena = dplyr::if_else((Fly_Id %% flies_per_arena) == 0,
                                             Fly_Id/flies_per_arena,
                                             ceiling(Fly_Id/flies_per_arena))
                      ) %>%
        dplyr::group_by(Video_name, Fly_Id, Frame)
    if (save_data) {
        cat(paste0("    Now saving csv\n"))
        SaveName <- paste0(tracking_dir_path, "Results/", vid_name,'_ALLDATA_R.csv.gz')
        fwrite(my_data, SaveName)
    }
    return(my_data)
}







extract_track_data <- function(file_path) {
    suppressMessages(library("data.table"))
    suppressMessages(library("tidyverse"))
    suppressMessages(library("R.matlab"))

    ufmf_track <- R.matlab::readMat(file_path)

    # names
    for (i in seq_along(ufmf_track[["trk"]][[1]])) {
        if (i == 1) {
            track_names <- list()
        }
        track_names[[i]] <- ufmf_track[["trk"]][[1]][[i]][[1]][1,1]
    }
    track_names <- unlist(track_names) %>% stringr::str_replace_all(" ", "_")
    track_units <- c("px", "px", "rad", "px", "px", "px", "px", "au", "px",
                     "px", "px", "px", "px", "rad", "px", "rad", "px", "px",
                     "px", "px", "px", "px", "px", "px", "px", "px", "px",
                     "px", "px", "rad", "rad", "rad", "rad", "rad", "rad")
    # default number of features in the track data is 35, but if FlyTrackerClassifySex_generic.mat
    # has been run, then there will be a 36th column, so we append another unit value to account
    # for this.
    if ( length(track_names) == 36 ) {
        track_units <- c(track_units, "au")
    }

    # flies.in.chamber
    for (i in seq_along(ufmf_track[["trk"]][[3]])) {
        if (i == 1) {
            fly_ids <- list()
        }
        fly_ids[[i]] <- tibble::tibble(Arena = rep(i,length(ufmf_track[["trk"]][[3]][[i]][[1]][1,])),
                                       Fly_Id = ufmf_track[["trk"]][[3]][[i]][[1]][1,])
    }
    fly_ids <- dplyr::bind_rows(fly_ids)

    # data
    for (i in seq_along(track_names)) {
        if (i == 1) {
            track_data <- list()
        }
        for (ii in seq_along(fly_ids$Fly_Id)) {
            if (ii == 1) {
                track_data_feature <- list()
            }
            track_data_feature[[ii]] <- tibble::tibble(Frame = 1:dim(ufmf_track[["trk"]][[2]])[2],
                                                       Fly_Id = fly_ids$Fly_Id[[ii]],
                                                       Feature = track_names[[i]],
                                                       Units = track_units[[i]],
                                                       Value = ufmf_track[["trk"]][[2]][ii,,i],
                                                       Data_Source = "track.mat"
            )
        }
        track_data[[i]] <- dplyr::bind_rows(track_data_feature)
    }
    track_data <- dplyr::bind_rows(track_data)

    # flags

    # ...

    # pull together
    track_data <- dplyr::right_join(fly_ids,track_data, by = "Fly_Id")

    return(track_data)
}

extract_feat_data <- function(file_path) {
    suppressMessages(library("data.table"))
    suppressMessages(library("tidyverse"))
    suppressMessages(library("R.matlab"))

    ufmf_feat <- R.matlab::readMat(file_path)

    # names
    feat_names <- unlist(ufmf_feat[["feat"]][[1]])
    ufmf_feat[["feat"]][[2]][[8]] <- ufmf_feat[["feat"]][[2]][[1]]
    ufmf_feat[["feat"]][[2]][[8]][[1]][1,1] <- "au"
    feat_units <- unlist(ufmf_feat[["feat"]][[2]])

    # data
    for (i in 1:dim(ufmf_feat[["feat"]][[3]])[3]) {
        if (i == 1) {
            feat_data <- list()
        }
        for (ii in 1:dim(ufmf_feat[["feat"]][[3]])[1]) {
            if (ii == 1) {
                feat_data_feature <- list()
            }
            feat_data_feature[[ii]] <- tibble::tibble(Frame = 1:dim(ufmf_feat[["feat"]][[3]])[2],
                                                      Fly_Id = ii,
                                                      Feature = feat_names[[i]],
                                                      Units = feat_units[[i]],
                                                      Value = ufmf_feat[["feat"]][[3]][ii,,i],
                                                      Data_Source = "feat.mat"
            )
        }
        feat_data[[i]] <- dplyr::bind_rows(feat_data_feature)
    }
    feat_data <- dplyr::bind_rows(feat_data)

    return(feat_data)
}

extract_jaaba_data <- function(dir_path,raw = FALSE) {
    suppressMessages(library("data.table"))
    suppressMessages(library("tidyverse"))
    suppressMessages(library("R.matlab"))

    i <- dplyr::if_else(raw, 1, 4)
    jaaba_scores_files <- list.files(dir_path) %>% stringr::str_subset("scores_") %>% stringr::str_subset("_id_corrected.mat")
    # if there are no files named '*_id_corrected.mat' then load the non-id_corrected files
    if (purrr::is_empty(jaaba_scores_files)) {
        id_corrected <- FALSE
        jaaba_scores_files <- list.files(dir_path) %>% stringr::str_subset("scores_") %>% stringr::str_subset(".mat")
    }
    for (ii in seq_along(jaaba_scores_files)) {
        if (ii == 1) {
            jaaba_scores <- list()
        }
        jaaba_scores_file <- R.matlab::readMat(paste0(dir_path,jaaba_scores_files[[ii]]))
        jaaba_behaviour <- jaaba_scores_files[[ii]] %>%
                                stringr::str_remove("scores_") %>%
                                stringr::str_remove("_id_corrected.mat") %>%
                                stringr::str_remove(".mat")
        for (iii in 1:length(jaaba_scores_file[["allScores"]][[1]])) {
            if (iii == 1) {
                jaaba_scores_ind <- list()
            }
            jaaba_scores_ind[[iii]] <- tibble::tibble(Frame = 1:length(jaaba_scores_file[["allScores"]][[i]][[iii]][[1]][1,]),
                                                      Fly_Id = iii,
                                                      Feature = jaaba_behaviour,
                                                      Units = dplyr::if_else(raw, "raw", "processed"),
                                                      Value = jaaba_scores_file[["allScores"]][[i]][[iii]][[1]][1,],
                                                      Data_Source = "jaaba"
            )
        }
        jaaba_scores[[ii]] <- dplyr::bind_rows(jaaba_scores_ind)
    }
    jaaba_scores <- dplyr::bind_rows(jaaba_scores)
    return(jaaba_scores)
}
